[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F030C8"
[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"

[target.thumbv6m-none-eabi.release]
codegen-units = "1"
opt-level = "z"
lto = "fat"
